package ExceptionHandling;

import java.util.InputMismatchException;
import java.util.Scanner;

/**
 * Main
 */
public class Main {
    public static void main(String[] args) throws MyCustomException {
        // Scanner scanner = new Scanner(System.in);

        // try{
        //     System.out.print("Enter first number: ");
        //     int number1 = scanner.nextInt();
        //     System.out.print("Enter second number: ");
        //     int number2 = scanner.nextInt();
        //     int answer = (number1 / number2);
        //     System.out.println("Answer is: " + answer);

        // } catch (InputMismatchException e) {
        //     System.out.println("Error: Invalid input for number");
        // } catch (ArithmeticException e) {
        //     System.out.println("Error: Division by zero");
        // } catch (Exception e) {
        //     System.out.println("Error: Unknown error");
        // } finally {
        //     scanner.close();
        // }

        // System.out.println("End of program");

        // Scanner scanner = new Scanner(System.in);
        // int num = scanner.nextInt();

        // if (num < 0) {
        //     throw new MyCustomException("Number is less than 0");
        // }
    }
}